steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/app-loja-online/aplicacao.yaml
  - --filename=kubernets/app-loja-online/deployment.yaml
  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test
  timeout: 2200s


