steps:

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t frontend:renew frontend/.
    docker tag frontend:renew gcr.io/bootcamp-363315/frontend:renew
    docker push gcr.io/bootcamp-363315/frontend:renew


