steps:

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t frontend:renew Docker-repos/frontend/.
    docker tag frontend:renew gcr.io/bootcamp-363315/frontend:renew
    docker push gcr.io/bootcamp-363315/frontend:renew

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/frontend.yml
  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test
  timeout: 1200s


