steps:

## criaçao do cluster gke 
- id: 'cluster-GKE'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    cd GKE-Prod
    terraform init
    terraform apply -auto-approve


- id: Deploy kubernets apply
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/backend.yml
  - --filename=kubernets/frontend.yml
  - --filename=kubernets/database.yml
  - --location=us-central1
  - --cluster=my-cluster-k8-produção
  timeout: 1200s






