steps:

- id: 'Deploy frontend'
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/frontend.yml
  - --location=us-central1
  - --cluster=my-cluster-k8
  timeout: 1200s

- id: 'Deploy database'
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/database.yml
  - --location=us-central1
  - --cluster=my-cluster-k8
  timeout: 1200s

- id: "Deploy backend"
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/backend.yml
  - --location=us-central1
  - --cluster=my-cluster-k8
  timeout: 1200s


  #Run DAST scan using OWASP ZAP in GCP DevSecOps Pipeline
- name: 'ubuntu'
  entrypoint: bash
  args: 
    - '-c'
    - |-
      apt-get update
      apt-get -y install wget
      apt-get -y install default-jdk
      wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Linux.tar.gz
      mkdir zap
      tar -xvf ZAP_2.11.1_Linux.tar.gz
      cd ZAP_2.11.1
      ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout ../zap_report.html 
  id: DAST Scan using OWASP ZAP
artifacts:
  objects:
    location: 'gs://securityguro'
    paths:
      - zap_report.html







