steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run

  # Frontend
  - --filename=kubernets/frontend.yml
  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test

  #backend

  - --filename=kubernets/backend.yml
  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test

  timeout: 1200s