steps:

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t frontend frontend/.
    docker tag frontend:renew gcr.io/bootcamp-363315/frontend:renew
    docker push gcr.io/bootcamp-363315/frontend:renew

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t database database/.
    docker tag database:renew gcr.io/bootcamp-363315/database:renew
    docker push gcr.io/bootcamp-363315/database:renew

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t backend backend/.
    docker tag backend:renew gcr.io/bootcamp-363315/backend:renew
    docker push gcr.io/bootcamp-363315/backend:renew


- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run

  # Frontend
  - --filename=kubernets/frontend.yml
  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test

  #backend

  - --filename=kubernets/backend.yml
  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test

 #database
 
  - --filename=kubernets/database.yml
  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test

  timeout: 1200s