steps:

- id: 'Deploy kubernetes'
  name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/database.yml
  - --location=us-central1
  - --cluster=my-cluster-k8
  - --filename=kubernets/backend.yml
  - --location=us-central1
  - --cluster=my-cluster-k8
  - --filename=kubernets/frontend.yml
  - --location=us-central1
  - --cluster=my-cluster-k8
  timeout: 2200s









