steps:


- id: 'tf apply cluster-GKE'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    cd Gke-devtest
    terraform init
    terraform apply -auto-approve
  timeout: 1200s

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=backend-1.0/php-deployment.yml
  - --filename=database-1.0/db-deployment.yml
  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test
  timeout: 1200s