steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/frontend.yml
  - --image=gcr.io/bootcamp-363315/frontend:latest
  - --location=us-central1-a
  - --cluster=my-cluster-k8
  timeout: 5200s
