steps:

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t frontend frontend/.
    docker tag frontend gcr.io/bootcamp-363315/frontend.yml
    docker push gcr.io/bootcamp-363315/frontend


- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run

  # Frontend
  - --filename=kubernets/froend.yml
  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test
  timeout: 1200s