steps:

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t frontend frontend/.
    docker tag frontend gcr.io/bootcamp-363315/frontend
    docker push gcr.io/bootcamp-363315/frontend

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t database database/.
    docker tag database gcr.io/bootcamp-363315/database
    docker push gcr.io/bootcamp-363315/database

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t backend backend/.
    docker tag backend gcr.io/bootcamp-363315/backend
    docker push gcr.io/bootcamp-363315/frontend


- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run

  # Frontend
  - --filename=kubernets/frontend.yml
  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test

  #backend

  - --filename=kubernets/backend.yml
  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test

 #database
 
  - --filename=kubernets/database.yml
  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test

  timeout: 1200s