steps:

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t backend:latest backend-1.0/.
    docker tag backend:latest us-central1-docker.pkg.dev/bootcamp-363315/backend:latest
    docker push us-central1-docker.pkg.dev/bootcamp-363315/backend:lates
  timeout: 1200s

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t database:latest database-1.0/.
    docker tag database:latest us-central1-docker.pkg.dev/bootcamp-363315/database:latest
    docker push us-central1-docker.pkg.dev/bootcamp-363315/database:latest
  timeout: 1200s
  

- id: 'tf apply cluster-GKE'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    cd 
    terraform init
    terraform apply -auto-approve
  timeout: 1200s

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=/backend-1.0/php-deployment.yml
  - --filename=/database-1.0/db-deployment.yml
  - --location=us-central1-a
  - --cluster=my-cluster-k8
  timeout: 1200s