steps:

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t frontend frontend/.
    docker tag frontend gcr.io/bootcamp-363315/backend
    docker push gcr.io/bootcamp-363315/backend