steps:

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t frontend:latest Docker-Projetos/frontend/.
    docker tag frontend:latest gcr.io/bootcamp-363315/frontend:latest
    docker push gcr.io/bootcamp-363315/frontend:latest

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t database:latest Docker-Projetos/database/.
    docker tag database:latest us-central1-docker.pkg.dev/bootcamp-363315/database/database:latest
    docker push us-central1-docker.pkg.dev/bootcamp-363315/database/database:latest

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t backend:latest Docker-Projetos/backend/.
    docker tag backend:latest us-central1-docker.pkg.dev/bootcamp-363315/backend/backend:latest
    docker push us-central1-docker.pkg.dev/bootcamp-363315/backend/backend:latest