steps:


- name: gcr.io/$PROJECT_ID/frontend
  args:
   - upgrade
   - -i
   - app
   - ./kubernets
   - --set
   - image.repository=us-central1-docker.pkg.dev/bootcamp-363315/frontend/frontend:lastest
   - -f
   - ./kubernets/frontend.yml
timeout: 1200s
substitutions:
  _CUSTOM_REGION: us-central1-a
  _CUSTOM_CLUSTER: my-cluster-k8
