steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/frontend.yml
  - --us-central1-docker.pkg.dev/bootcamp-363315/frontend/frontend:latest
  - --location=us-central1-a
  - --cluster=my-cluster-k8
  timeout: 1200s


- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/backend.yml
  - --image=us-us-central1-docker.pkg.dev/bootcamp-363315/backend
  - --location=us-central1-a
  - --cluster=my-cluster-k8
  timeout: 1200s

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/database.yml
  - --image=us-central1-docker.pkg.dev/bootcamp-363315/database
  - --location=us-central1-a
  - --cluster=my-cluster-k8
  timeout: 1200s


