steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t database .
    docker tag database:latest
    docker push us-central1-docker.pkg.dev/bootcamp-363315/database