steps:

- id: 'docker database'
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t database:latest database/.
    docker tag database:latest us-central1-docker.pkg.dev/bootcamp-363315/database/database:latest
    docker push us-central1-docker.pkg.dev/bootcamp-363315/database/database:latest
- id: 'docker frontend'
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t frontend:latest frontend/.
    docker tag frontend:latest us-central1-docker.pkg.dev/bootcamp-363315/frontend/frontend:latest
    docker push us-central1-docker.pkg.dev/bootcamp-363315/frontend/frontend:latest