- name: node
  entrypoint: npm
  args: ['install']
# Run tests
- name: node
  entrypoint: npm
  args: ['test']
# Run custom commands
- name: node
  entrypoint: npm
  args: ['run', 'build']
      

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t frontend:renew frontend/.
    docker tag frontend:renew us-central1-docker.pkg.dev/bootcamp-363315/frontend/frontend:renew
    docker push us-central1-docker.pkg.dev/bootcamp-363315/frontend/frontend:renew