steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/kube.yml
  - --filename=kubernets/pok8s.yml
  - --filename=kubernets/gcloud.yml
  - --location=southamerica-east1
  - --cluster=my-gke-cluster-devtest
  timeout: 1200s
