steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/k8pod.yml
  - --filename=kubernets/skaffold.yml
  timeout: 1200s

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/gcloud.yml
  - --location=us-central1-f
  - --cluster=my-cluster-k8-devtest
  timeout: 1200s




