steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run

  # apply -f deployements
  - --filename=deployements/worker.yaml
  - --filename=deployements/redis.yaml
  - --filename=deployements/result.yaml
  - --filename=deployements/vote.yaml
  - --filename=deployements/db.yaml


  ## servidor gke-test - regiao F

  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test
  timeout: 5200s # tempo de execução


