steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  
  ### apply -f namespaces

  - --filename=namespaces/vote.yaml

  # apply -f deployements
  - --filename=deployements/redis.yaml
  - --filename=deployements/resut.yaml
  - --filename=deployements/vote.yaml
  - --filename=deployements/db.yaml

  # apply -f services

  - --filename=services/db.yaml
  - --filename=services/redis.yaml
  - --filename=services/vote.yaml
  - --filename=services/resut.yaml

  ## servidor gke-test - regiao F

  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test
  timeout: 5200s # tempo de execução


