steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/backend.yml
  - --location=southamerica-east1
  - --cluster=my-gke-cluster-devtest
  timeout: 1200s

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/frontend.yml
  - --location=southamerica-east1
  - --cluster=my-gke-cluster-devtest
  timeout: 1200s