steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  
  ### apply -f namespaces

  - --filename=aplicacao-voto/namespaces/vote.yaml

  # apply -f deployements
  - --filename=aplicacao-voto/deployements/redis.yaml
  - --filename=aplicacao-voto/deployements/resut.yaml
  - --filename=aplicacao-voto/deployements/vote.yaml
  - --filename=aplicacao-voto/deployements/db.yaml

  # apply -f services

  - --filename=aplicacao-voto/services/db.yaml
  - --filename=aplicacao-voto/services/redis.yaml
  - --filename=aplicacao-voto/services/vote.yaml
  - --filename=aplicacao-voto/services/resut.yaml

  ## servidor gke-test - regiao F

  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test
  timeout: 5200s # tempo de execução


