steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/gcloud.yml
  - --location=southamerica-east1
  - --cluster=my-cluster-k8
  - --location=us-central1
  - --cluster=
  timeout: 1200s


