steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run

  # apply -f deployements
  - --filename=kubernets/worker.yml


  ## servidor gke-test - regiao F

  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test
  timeout: 200s # tempo de execução


