steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/backend.yml
  - --filename=kubernets/service.yml
  - --delivery-pipeline=ci-cd-test
  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test
  timeout: 1200s