steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/deployment-frontend.yml
  - --filename=kubernets/service-frontend.yml
  - --location=us-central1-f
  - --cluster=my-cluster-k8-devtest
  timeout: 200s

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "PIPELINE_NAME",
      "--region", "us-central1",
      "--annotations", "commitId=${REVISION_ID}",
      "--build-artifacts", "/workspace/artifacts.json"