steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/skaffold.yml
  - --filename=kubernets/k8pod.yml
  - --filename=kubernets/gcloud.yml
  - --location=us-central1
  - --cluster=my-cluster-k8-devtest
  - --cluster=my-cluster-k8
  timeout: 200s