steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/backend.yml
  - --filename=kubernets/backend.yml
  - --location=us-central1-f
  - --cluster=my-cluster-k8
  timeout: 1200s


