steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/gcloud.yml
  - --location=us-central1
  - --project=bootcamp-363315
  - --cluster=my-cluster-k8-devtest
  - --cluster=my-cluster-k8
  timeout: 1200s


