steps:

### docker compilaçao do cointainer backend
- id: 'Backend'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t backend Docker-Projetos/backend/.
    docker tag backend gcr.io/bootcamp-363315/backend
    docker push gcr.io/bootcamp-363315/backend

- id: 'Frontend'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t backend Docker-Projetos/backend/.
    docker tag backend gcr.io/bootcamp-363315/backend
    docker push gcr.io/bootcamp-363315/backend







  

  