steps:


### docker compilaçao do cointainer database
- id: Database
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t database Docker-Projetos/database/.
    docker tag database gcr.io/bootcamp-363315/database
    docker push gcr.io/bootcamp-363315/database

### docker compilaçao do cointainer backend
- id: backend
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t backend Docker-Projetos/backend/.
    docker tag backend gcr.io/bootcamp-363315/backend
    docker push gcr.io/bootcamp-363315/backend







  

  