apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: delivery-skaffold-gke
description: Delivery Pipeline for a sample java app
serialPipeline:
  stages:
    - targetId: my-cluster-k8-dev-test
    - targetId: my-cluster-k8

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: my-cluster-k8-dev-test
description: A Dev cluster
gke:
  cluster: projects/bootcamp-363315/locations/us-central1/clusters/my-cluster-k8-dev-test

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: my-cluster-k8
description: A Prod cluster
requireApproval: true
gke:
  cluster: projects/bootcamp-363315/locations/us-central1/clusters/my-cluster-k8
