apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-cloud-sql-quickstart
spec:
  selector:
    matchLabels:
      app: gke-cloud-sql-app
  template:
    metadata:
      labels:
        app: gke-cloud-sql-app
    spec:
      containers:
      - name: gke-cloud-sql-app
        image: southamerica-east1-docker.pkg.dev/bootcamp-363315/gke-cloud-sql-repo/gke-sql:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: INSTANCE_HOST
          value: "34.136.172.168"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: root
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mypassw0rd
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: meubanco
              key: database
