apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 10
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/bootcamp-363315/backend:latest
        ports:
          - containerPort: 80
            name: frontend 
            env:
            - name: PORT
              value: "8080"
            - name: INSTANCE_HOST
              value: "34.136.172.168"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
              secretKeyRef:
                name: root
                key: username
            - name: DB_PASS
              valueFrom:
              secretKeyRef:
                name: mypassw0rd
                key: password
            - name: DB_NAME
              valueFrom:
              secretKeyRef:
                name: meubanco
                key: database
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30005
  selector:
    app: php