steps:

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
    docker build -t backend:renew Docker-repos/backend/.
    docker tag backend:renew gcr.io/bootcamp-363315/backend/backend:renew
    docker push gcr.io/bootcamp-363315/backend/backend:renew

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/backend.yml
  - --location=us-central1-f
  - --cluster=my-cluster-k8-dev-test
  timeout: 1200s

      


