steps:

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernets/namespaces.yml
  - --filename=kubernets/frontend.yml
  - --location=us-central1-a
  - --cluster=my-cluster-k8
  timeout: 1200s

      


