apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: gcr.io/bootcamp-363315/database:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_DATABASE
          value: "meubanco"
        - name: MYSQL_USER
          value: ""
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "Senha123"