apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: us-central1-docker.pkg.dev/bootcamp-363315/frontend/frontend@sha256:9fa3e5da326b6c21ac28c9f3ae63bff556a7bd51139ea290153721a7f26f2c4b
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  type: LoadBalancer
  selector:
    app: website
  ports:
    - port: 80
      targetPort: 80