apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 10
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/bootcamp-363315/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: frontend
description: Hello World Deployment Pipeline 
serialPipeline:
  stages:
  - targetId: my-gke-cluster-devtest
  - targetId: my-cluster-k8
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: my-gke-cluster-devtest
description: my-gke-cluster-devtest cluster 
gke:
  cluster: projects/bootcamp-363315/locations/southamerica-east1/clusters/my-gke-cluster-devtest

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: my-cluster-k8
description: my-cluster-k8 cluster 
gke: 
  cluster: projects/bootcamp-363315/locations/us-central1/clusters/my-cluster-k8