apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: hello-world-app
description: Hello World Deployment Pipeline 
serialPipeline:
 stages:
 - targetId: my-cluster-k8-devtest
   profiles: []
 - targetId: my-cluster-k8
   profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-cluster-k8-devtest
description: my-gke-cluster-devtest cluster 
gke:
  cluster: projects/bootcamp-363315/locations/us-central1/clusters/my-cluster-k8-devtest

---
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-cluster-k8
description: my-cluster-k8 cluster 
gke: 
  cluster: projects/bootcamp-363315/locations/us-central1/clusters/my-cluster-k8

