apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: pipeline-k8
description: main application pipeline
serialPipeline:
 stages:
 - targetId: my-cluster-k8-dev-test
   profiles: []
 - targetId: my-cluster-k8-dev-staging
   profiles: []
 - targetId: my-cluster-k8
   profiles: []
 
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: my-cluster-k8-devtest
description: cluster-test
gke:
 cluster: projects/bootcamp-363315/locations/us-central1/clusters/my-cluster-k8-dev-test
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: my-cluster-k8-dev-staging
description: cluster-staging
requireApproval: true
gke:
 cluster: projects/bootcamp-363315/locations/us-central1/clusters/my-cluster-k8-dev-staging
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: my-cluster-k8
description: cluster-produçao
gke:
 cluster: projects/bootcamp-363315/locations/us-central1/clusters/my-cluster-k8