apiVersion: skaffold/v2beta16
kind: Config
deploy:
  kubectl:
    manifests:
      - k8s-*
---
apiVersion: v1
kind: Pod
metadata:
  name: getting-started
spec:
  containers:
  - name: frontend
    image: gcr.io/bootcamp-363315/frontend:latest
---
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: my-gke-demo-app-1
description: main application pipeline
serialPipeline:
 stages:
 - targetId: qsdev
   profiles: []
 - targetId: qsprod
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsdev
description: development cluster
gke:
 cluster: projects/bootcamp-363315/locations/us-central1/clusters/my-cluster-k8