apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
 name: my-gke-demo-app-1
description: main application pipeline
serialPipeline:
 stages:
 - targetId: my-cluster-k8-devtest
   profiles: []
 - targetId: my-cluster-k8
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: my-cluster-k8-devtest
description: development cluster
gke:
 cluster: projects/bootcamp-363315/locations/us-central1/clusters/my-cluster-k8-devtest
---

apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
 name: my-cluster-k8
description: production cluster
gke:
 cluster: projects/bootcamp-363315/locations/us-central1/clusters/my-cluster-k8

