apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: frontend
description: Hello World Deployment Pipeline 
serialPipeline:
  stages:
  - targetId: my-gke-cluster-devtest
  - targetId: my-cluster-k8
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: my-gke-cluster-devtest
description: my-gke-cluster-devtest cluster 
gke:
  cluster: projects/bootcamp-363315/locations/southamerica-east1/clusters/my-gke-cluster-devtest