apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: app-frontend-service
description: Hello World Deployment Pipeline 
serialPipeline:
 stages:
 - targetId: my-gke-cluster-devtest
   profiles: []
 - targetId: my-cluster-k8
   profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: my-gke-cluster-devtest
description: my-gke-cluster-devtest cluster 
gke:
  cluster: projects/bootcamp-363315/locations/southamerica-east1/clusters/my-gke-cluster-devtest

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: my-cluster-k8
description: my-cluster-k8 cluster 
gke: 
  cluster: projects/bootcamp-363315/locations/us-central1/clusters/my-cluster-k8