apiVersion: v1
kind: Deployment
metadata:
  name: getting-started
spec:
  containers:
      - name: frontend
        image: gcr.io/bootcamp-363315/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: my-gke-demo-app-1
description: main application pipeline
serialPipeline:
 stages:
 - targetId: qsdev
   profiles: []
 - targetId: qsprod
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsdev
description: development cluster
gke:
 cluster: projects/bootcamp-363315/locations/us-central1/clusters/my-cluster-k8